spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  data:
    solr:
      host: http://47.100.170.141:8088/solr/

dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 47.100.170.141:2181
  protocol:
    port: 28811

server:
  port: 8081
